
tap "romkatv/powerlevel10k"
tap "homebrew/cask-fonts"

brew "git"
brew "kubectl"
brew "zsh"
brew "curl"
brew "tree"
brew "openssl"
brew "telnet"
brew "grep"
brew "lsd"
brew "jq"
brew "testssl"
brew "openssh" # ed25519-sk

cask "font-meslo-lg-nerd-font"
cask "font-hack-nerd-font"
cask "firefox"
cask "visual-studio-code"
cask "iterm2"
cask "alfred"
cask "alt-tab"
cask "docker"
cask "lens"
cask "homebrew/cask-drivers/logitech-options"
cask "yubico-yubikey-manager"
cask "hiddenbar"
cask "microsoft-remote-desktop"
cask "slack"

#mas: hiddenme
