[character]
#symbol = "➜"
success_symbol = "[✔](bold green)"
error_symbol = "[✗](bold red)"

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_range = "08:00:00-16:00:00"

# Show the current directory
[directory]
truncation_length = 3

